#!/usr/bin/env bash
# Install nginx web server


ssh -i ~/.ssh/school ubuntu@52.91.135.223
sudo apt -y update
# sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.nginx-debian.html
