#!/usr/bin/env bash
# Install nginx web server


sudo apt-get -y update
# Install Nginx
sudo apt-get -y install nginx

# Create a server block
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Enable the server block
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Create a test HTML file
echo "Hello World!" | sudo tee /var/www/html/index.html
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Restart Nginx without using systemctl
sudo service nginx restart
