#!/usr/bin/env bash
# Update package list and install nginx

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /etc/nginx/sites-enabled

sudo echo  "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-enabled/default

service nginx restart
# curl -sI localhost/redirect_me | grep "301 Moved Permanently" > /dev/null
# if [ $? -eq 0 ]; then
#     echo "Nginx is running and redirection is working"
# else
#     echo "Nginx redirection is not working"
#     exit 1
# fi
