#!/usr/bin/env bash
# Update package list and install nginx

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL

service nginx restart
curl -sI localhost/redirect_me | grep "301 Moved Permanently" > /dev/null
if [ $? -eq 0 ]; then
    echo "Nginx is running and redirection is working"
else
    echo "Nginx redirection is not working"
    exit 1
fi
