#!/usr/bin/env bash
#writes "Best School" on the terminal
counter=0
while [ $counter -lt 10 ]
do
    if [ $counter -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
